// Generated by Sichem at 2020-09-30 18:30:48

using System;
using System.Runtime.InteropServices;
using static CRuntime;

namespace ZlibSharp
{
	unsafe class Adler32
	{
		public static sbyte*[] z_errmsg = new sbyte[10];
		[StructLayout(LayoutKind.Sequential)]
		public class z_stream_s
	{
		public byte* next_in;
		public uint avail_in;
		public int total_in;
		public byte* next_out;
		public uint avail_out;
		public int total_out;
		public string msg;
		public internal_state state;
		public zalloc_delegate zalloc;
		public zfree_delegate zfree;
		public void * opaque;
		public int data_type;
		public int adler;
		public int reserved;
		}
		[StructLayout(LayoutKind.Sequential)]
		public struct gz_header_s
	{
		public int text;
		public int time;
		public int xflags;
		public int os;
		public byte* extra;
		public uint extra_len;
		public uint extra_max;
		public byte* name;
		public uint name_max;
		public byte* comment;
		public uint comm_max;
		public int hcrc;
		public int done;
		}
		[StructLayout(LayoutKind.Sequential)]
		public struct gzFile_s
	{
		public uint have;
		public byte* next;
		public long pos;
		}
		public static int adler32_z(int adler, byte* buf, ulong len)
		{
			int sum2 = 0;
			uint n = 0;
			sum2 = (int)((adler >> 16) & 0xffff);
			adler &= (int)(0xffff);
			if ((len) == (1)) {
adler += (int)(buf[0]);if ((adler) >= (65521U)) adler -= (int)(65521U);sum2 += (int)(adler);if ((sum2) >= (65521U)) sum2 -= (int)(65521U);return (int)(adler | (sum2 << 16));}

			if ((buf) == (null)) return (int)(1L);
			if ((len) < (16)) {
while ((len--) != 0) {
adler += (int)(*buf++);sum2 += (int)(adler);}if ((adler) >= (65521U)) adler -= (int)(65521U);sum2 %= (int)(65521U);return (int)(adler | (sum2 << 16));}

			while ((len) >= (5552)) {
len -= (ulong)(5552);n = (uint)(5552 / 16);do {
{
adler += (int)((buf)[0]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 2 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4 + 2 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 2 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4 + 2 + 1]);sum2 += (int)(adler);}
buf += 16;}
 while ((--n) != 0);adler %= (int)(65521U);sum2 %= (int)(65521U);}
			if ((len) != 0) {
while ((len) >= (16)) {
len -= (ulong)(16);{
adler += (int)((buf)[0]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 2 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[0 + 4 + 2 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 2 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4 + 1]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4 + 2]);sum2 += (int)(adler);}
{
adler += (int)((buf)[8 + 4 + 2 + 1]);sum2 += (int)(adler);}
buf += 16;}while ((len--) != 0) {
adler += (int)(*buf++);sum2 += (int)(adler);}adler %= (int)(65521U);sum2 %= (int)(65521U);}

			return (int)(adler | (sum2 << 16));
		}

		public static int adler32(int adler, byte* buf, uint len)
		{
			return (int)(adler32_z((int)(adler), buf, (ulong)(len)));
		}

		public static int adler32_combine_(int adler1, int adler2, long len2)
		{
			int sum1 = 0;
			int sum2 = 0;
			uint rem = 0;
			if ((len2) < (0)) return (int)(0xffffffffUL);
			len2 %= (long)(65521U);
			rem = ((uint)(len2));
			sum1 = (int)(adler1 & 0xffff);
			sum2 = (int)(rem * sum1);
			sum2 %= (int)(65521U);
			sum1 += (int)((adler2 & 0xffff) + 65521U - 1);
			sum2 += (int)(((adler1 >> 16) & 0xffff) + ((adler2 >> 16) & 0xffff) + 65521U - rem);
			if ((sum1) >= (65521U)) sum1 -= (int)(65521U);
			if ((sum1) >= (65521U)) sum1 -= (int)(65521U);
			if ((sum2) >= ((int)(65521U) << 1)) sum2 -= (int)((int)(65521U) << 1);
			if ((sum2) >= (65521U)) sum2 -= (int)(65521U);
			return (int)(sum1 | (sum2 << 16));
		}

		public static int adler32_combine(int adler1, int adler2, int len2)
		{
			return (int)(adler32_combine_((int)(adler1), (int)(adler2), (long)(len2)));
		}

		public static int adler32_combine64(int adler1, int adler2, long len2)
		{
			return (int)(adler32_combine_((int)(adler1), (int)(adler2), (long)(len2)));
		}

}
}